on:
  push:
    branches: [master]

name: Build Release
jobs:
  Build-Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Setup flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - name: Build flutter
        run: |
          flutter pub get
          flutter build windows
        


