on:
  push:
    branches: [master]

name: Build Release
jobs:
  Build-Windows-Release:
    runs-on: windows-latest
    steps:
      if: startsWith(github.ref, 'refs/tags/')
      - uses: actions/checkout@master
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Setup flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - name: Build flutter
        run: |
          flutter config --enable-windows-desktop
          flutter pub get
          flutter build windows
      - name: Zip Artifacts
        uses: papeloto/action-zip@v1
        with:
          files: build/windows/runner/Release
          dest: cfip-windows.zip
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files:
            cfip-windows.zip
